name: Update Server Status
on:
  schedule:
    - cron: '0 * * * *' # This runs the script every hour

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the status update script
        run: |
          python check_server_status.py

      - name: Check out the wiki
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki-repo

      - name: Move the status file to the wiki
        run: |
          mv Server_Status.md wiki-repo/

      - name: Commit and push changes to the wiki
        run: |
          git -C wiki-repo add Server_Status.md
          git -C wiki-repo commit -m "Update server status"
          git -C wiki-repo push https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.wiki.git
